#!/bin/bash

# ASCII Art
ascii_art="
 ____  ____   ____    _    __  __ _____ ____  
/ ___||  _ \ / ___|  / \  |  \/  | ____|  _ \ 
\___ \| | | | |  _  / _ \ | |\/| |  _| | |_) |
 ___) | |_| | |_| |/ ___ \| |  | | |___|  _ < 
|____/|____/ \____/_/   \_\_|  |_|_____|_| \_\
                                              
"

# Colors
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Clear the screen and print banner
clear
echo -e "${CYAN}$ascii_art${NC}"

# Update package list and install dependencies
sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

# Wings

git clone git clone https://github.com/hydren-dev/HydraDAEMON.git
cd HydraDAEMON
npm install

echo_message "* cd HydraDAEMON"

echo_message "* paste your configure code"

echo_message "* node . or pm2 start ."
